const Home = () => {
    return (
        <>
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
         Ready to make some change? Want to help write the next chapter in the Story of Stuff? Whatever you have to offer, a better future needs it! Take our Changemaker Personality Quiz to see how you show up in the world and what role you can play in the Story of Stuff Community and beyond. Then share your results with your friends!
        </>
    );
}

export default Home;